name: grapecpg
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.18
  - pip
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu118
      - numpy==1.26.4
      - scipy==1.11.4
      - scikit-learn==1.3.2
      - torch==2.0.1+cu118
      - torch-geometric==2.3.1
